import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import About from "../components/About";
import Testimonials from "../components/Testimonials";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Krn Chauhan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <About />
        <Projects />
        <Skills />
        {/* <Testimonials /> */}
        {/* <Contact /> */}
      </main>
    </div>
  );
}
